# Arquivo: /n8n/Dockerfile

# Usa a imagem oficial do n8n como base
FROM docker.n8n.io/n8nio/n8n

# Muda para o usuário root para poder instalar pacotes
USER root

# Atualiza a lista de pacotes e instala o ffmpeg
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Volta para o usuário padrão do n8n
USER node